---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: ansible-role-libvirt-kickstart
      vars:
        root_password: test
        libvirt_host: localhost
        vm_name: test-vm
        vm_type: centos8
        vm_ip_address: '10.1.1.2'
        vm_netmask: 255.255.255.0
        vm_gateway: 10.1.1.1
        vm_nameserver: 10.1.1.1
